---
- hosts: web
  sudo: yes

  tasks:
      - name: "ls centos"
        command: ls
        when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") or
              (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")
...
