---
- hosts: web
  sudo: yes

  vars:
    web_server4: httpd

  tasks:
  - name: Ensure that Apache is installed
    yum: name={{web_server4}} state=present
  - name: Start Apache Services
    service: name={{web_server4}} enabled=yes state=started
...
