---
- hosts: web
  sudo: yes

  tasks:
    - name: "shut down CentOS 6 systems"
      command: touch /opt/verizon.txt
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7"
...
