---
# This playbook tests the script module on Windows hosts

- name: Run powershell script
  hosts: win
  gather_facts: false
  tasks:
    - name: Run powershell script
      script: files/Helloworld.ps1
      args:
        chdir: C:/Users/Admininstrator
...
